export default {
  XHR_SENT: "XHR_SENT",
  XHR_STATE_CHANGED: "XHR_STATE_CHANGED",
  XHR_PROGRESS: "XHR_PROGRESS",
  XHR_LOADED: "XHR_LOADED",
  FETCH_SENT: "FETCH_SENT",
  FETCH_STATE_CHANGED: "FETCH_STATE_CHANGED",
};
